### ISSUE TITLE
To do Entrega 2

### ISSUE THREAD

**Issue by viniciussousazup** [JhonnyBn/TheLastMage#8]
# Entrega 2
- [x] Toda a comunicação deverá ser substituída por gRPC;
- [ ] A operação a ser executada deve ser definida pela função, não por parâmetro (por exemplo, use funções “somar” e “subtrair”, não uma única função “calcular” com parâmetro indicando se é para somar ou subtrair);
- [x] O estado armazenado no servidor deve ser composto por log + snapshots dos dados;
Um texto de até uma página explica como e porquê Log Structured Merge Trees seriam usadas no projeto
## Outros elements dependerão de cada trabalho, com duas opções (Acho que no nosso caso vai ser consistent hashing):
- [ ] O serviço será particionado usando consistent hashing;
- [ ] O roteamento entre pares é feito via finger table;
- [x] Os dados são particionados usando alguma chave que os identifique;

**Comment by JhonnyBn** [comment]
Done
